### ISSUE TITLE
Unnecessary parameter in the demo?

### ISSUE THREAD

**Issue by vitaly-t** [iceddev/pg-transact#1]
In your demo for promises you still pass parameter 'cb' into the transaction function where it is not even used. Is it not meant to be used there or is there a mistake in the code?

Please clarify and correct the demo.

**Comment by phated** [comment]
Good catch.  Luckily it doesn't matter because we use `Promise#race` to complete when either the first condition is done instead of function arity like worse libraries.

**Comment by vitaly-t** [comment]
That's what I was hoping it was, as I'm relying on it to work correctly in all of my code.

Thank you for this library!
