### ISSUE TITLE
heads-up :)

### ISSUE THREAD

**Issue by vitaly-t** [iceddev/pg-transact#2]
Last December when I tried to use your library, I had to write my own version eventually, as my project relied on use of Promise heavily. I needed something like your library, but built essentially on promises for use both inside and outside of transactions.

After finishing that project just recently, I've finally come around to rewriting it for public consumption as pg-promise: https://www.npmjs.com/package/pg-promise

I'm still working on the first draft, and it's not on GitHub just yet, though it will soon, just as the first draft is finished. Feel free throwing stones at it ;)

Just so, you should update your library, as PG.JS got depreciated in favour of PG package.

**Comment by phated** [comment]
The use cases are different for what you are talking about and this module.  This module allows you to expose any API you want inside a transaction block and is expected to be the building block for libraries.

Btw, you are not allowed to squat names on npm.  If you don't have real code, they will remove it.

**Comment by vitaly-t** [comment]
Me squating names? :) The library has already been published there, you can see it running "npm install pg-promise". The first draft is pretty much finished, I'm just testing it. I hope it looks real :)

And yes, my approach is very different from yours :)
